branches:
  only:
    - version_5.0
    - configure_travis
gemfile:
  - gemfiles/Gemfile.rails-4.1.x
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
rvm:
  - 1.9.3
script: bundle exec rspec