branches:
  only:
    - version_5.0
    - configure_travis
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-edge
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
script: bundle exec rspec